version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - pip install --upgrade pip pipenv
      - pipenv install --dev --deploy

  build:
    commands:
      - export QA_STACK_OUTPUT_PATH="$CODEBUILD_SRC_DIR_QaStackOutput/output.json"
      - pipenv run pytest tests_integration/ -v
